### ISSUE TITLE
get_current_price() returning none for everything

### ISSUE THREAD

**Issue by agastya29** [JECSand/yahoofinancials#57] opened 2020-03-07 08:18 UTC
stock = YahooFInancials('ABB.BO')
cmp = stock.get_current_price()
cmp

returns None

Also happening with atleast volumes and market cap fields as well.

**Comment by thelawlaw** [comment] 2020-03-08 09:08
Same here... API is returning None...

Can the creator please solve?

**Comment by andres0820m** [comment] 2020-03-08 12:45
same over here

**Comment by georgk10** [comment] 2020-03-08 13:35
Same problem here. The way yahoo formats their data seems to have changed. I'm getting None for every request I make. A few days ago everything worked like a charm.

**Comment by agastya29** [comment] 2020-03-09 16:54
hi, 

So I found some time to go through the source code and how Yahoo Finance pages show the data. When I wrote my own version of YahooFinanceETL, I could get the data from Yahoo Finance like before. On comparing with YahooFInanceETL code, I can clearly see the same approach- using requests & bs4 using the same markers and regex statements, broadly speaking. The change required is minor which I am so far unable to pin point, mainly due to lack of time. For the original author, it should be 5-10min job max. Hope it helps. 
As a temporary fix, especially if you are looking for a limited number of fields, my suggestion is to write down a simple alternate to YahooFInanceETL and let YahooFinancials class inherit from that class. It works pretty much like the original. 
In case someone is lost, please go through the source code of YahooFinancials and YahooFinanceETL using the module 'inspect'. 
Hope it helps till the problem is fixed. Good Luck.

**Comment by almalh** [comment] 2020-03-10 01:44
Same problem here, hopefully it will be resolved soon

**Comment by sucubitos** [comment] 2020-03-10 13:11
I have also the same problem. I can get historical data for any stock till 6th of March, since then all I get is None. Hope the info helps to solve the problem.

**Comment by agastya29** [comment] 2020-03-11 05:04
> I have also the same problem. I can get historical data for any stock till 6th of March, since then all I get is None. Hope the info helps to solve the problem.

Please check again. Historical prices are working for me even now.

**Comment by bohm66** [comment] 2020-03-13 08:16
For me it is still None. When the problem started I ran my program several times and sometimes  I got "None" and some times I got the stock price. Now it is only "None".

**Comment by bohm66** [comment] 2020-03-13 08:18
> 
> 
> > I have also the same problem. I can get historical data for any stock till 6th of March, since then all I get is None. Hope the info helps to solve the problem.
> 
> Please check again. Historical prices are working for me even now.

Hi, did the original start working again? For me it is still "None" in the response

**Comment by georgk10** [comment] 2020-03-13 08:37
Since this issue seems not to be solved anytime soon I migrated to using [this library](https://github.com/ranaroussi/yfinance) . It works pretty well, although it had a small [bug](https://github.com/ranaroussi/yfinance/issues/214) - but this one has a solution already (which can really be fixed in less than a minute be anyone).

**Comment by hrodv** [comment] 2020-03-14 15:55
All key statistics still gives None. Do the developer plan to fix this issue?

**Comment by sylvandb** [comment] 2020-03-14 22:10
The issue is likely due to the client version. Fixed in my version, but there is also a slight change in API compared to this version -- mine always returns a dict as if you had requested multiple tickers.

https://github.com/sylvandb/yahoofinancials/

**Comment by scorpion-inc** [comment] 2020-03-15 15:06
> The issue is likely due to the client version. Fixed in my version, but there is also a slight change in API compared to this version -- mine always returns a dict as if you had requested multiple tickers.
> 
> https://github.com/sylvandb/yahoofinancials/

This worked for me.  However for me the comment "yahoo issue was the client version" wasn't completely clear as to how to fix.  So I thought I'd add a comment if others were in the same boat.

Line 71 needs to change from:
`version = 'Mozilla/5.0 (Windows; U; Windows NT 5.1; it; rv:1.8.1.11) Gecko/20071127 Firefox/2.0.0.11'`

to this:
`version = 'w3m/0.5.3+git20180125'`

Thanks sylvandb.

**Comment by bohm66** [comment] 2020-03-16 08:42
> 
> 
> > The issue is likely due to the client version. Fixed in my version, but there is also a slight change in API compared to this version -- mine always returns a dict as if you had requested multiple tickers.
> > https://github.com/sylvandb/yahoofinancials/
> 
> This worked for me. However for me the comment "yahoo issue was the client version" wasn't completely clear as to how to fix. So I thought I'd add a comment if others were in the same boat.
> 
> Line 71 needs to change from:
> `version = 'Mozilla/5.0 (Windows; U; Windows NT 5.1; it; rv:1.8.1.11) Gecko/20071127 Firefox/2.0.0.11'`
> 
> to this:
> `version = 'w3m/0.5.3+git20180125'`
> 
> Thanks sylvandb.

Hi, I do not understand. Is there a need to change the library or do I need to do something with the version in my code?

Thanks, Christer

**Comment by scorpion-inc** [comment] 2020-03-16 12:57
You fix one line in your code.  

Find the yahoofinancials package on your system, (mine is in the site-packages area of my python installation) then make the change in the file named __init__.py, which should be the only file in the yahoofinancials directory.

Alternatively you could install sylvandb's fork of this codebase (follow his link above).  For me, it was easier to fix the one line.

**Comment by scorpion-inc** [comment] 2020-03-16 12:58
Sorry, the comment system took off the underscores in the filename, I guess they are special characters.  The file you modify is named `__init__.py`

**Comment by bohm66** [comment] 2020-03-16 13:56
> 
> 
> Sorry, the comment system took off the underscores in the filename, I guess they are special characters. The file you modify is named `__init__.py`

.. and just by magic it starts to work!

Thanks, Christer

**Comment by opbankolia0** [comment] 2020-05-16 19:46
> > The issue is likely due to the client version. Fixed in my version, but there is also a slight change in API compared to this version -- mine always returns a dict as if you had requested multiple tickers.
> > https://github.com/sylvandb/yahoofinancials/
> 
> This worked for me. However for me the comment "yahoo issue was the client version" wasn't completely clear as to how to fix. So I thought I'd add a comment if others were in the same boat.
> 
> Line 71 needs to change from:
> `version = 'Mozilla/5.0 (Windows; U; Windows NT 5.1; it; rv:1.8.1.11) Gecko/20071127 Firefox/2.0.0.11'`
> 
> to this:
> `version = 'w3m/0.5.3+git20180125'`
> 
> Thanks sylvandb.

worked for me. thanks.

**Closed** 2020-10-18 23:14 UTC
