### ISSUE TITLE
ValueError: Invalid padding bytes.

### ISSUE THREAD

**Issue by pabgone** [JECSand/yahoofinancials#133] opened 2023-02-10 16:19 UTC
Hello,

An error is recently showing up when extracting any data with the library. I guess it has something to do with a change in Yahoo webpage. Is there any way to make it work fast? Like using a previous version or changing a couple of lines?

File "C:\Users\PABLO\Desktop\StockAnalyzerApp\venv\lib\site-packages\cryptography\hazmat\primitives\padding.py", line 101, in _byte_unpadding_check
    raise ValueError("Invalid padding bytes.")
ValueError: Invalid padding bytes.

**Comment by JECSand** [comment] 2023-02-11 01:07
@pabgone I planned on investigating/fixing it this weekend. There’s likely no easy quick fix to this. Yahoo is making it harder to extract financial data.

**Comment by JECSand** [comment] 2023-02-11 01:07
duplicate of #132

**Closed by JECSand** 2023-02-11 01:07 UTC

**Comment by pabgone** [comment] 2023-02-11 01:18
Thank you! I really appreciate it
